# -*- coding: utf-8 -*-
"""00_First_Analysis_IsTheWorldReadyForTheNextPandemic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTF0HqdySBd0DAXgzWd2Wjyj8mQAqtjS

## IsTheWorldReadyForTheNextPandemic - Mini Project
### Project handled by Liza, Ravit, Hagit and Hodaya

**This is a guided starter notebook, not a solution.**
TBD

---
## Part 1 · Setup, data
"""

from google.colab import drive
drive.mount('/content/drive')

# Core imports.
import numpy as np
np.random.seed(42)  # For reproducibility
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set the path where your DataSet CSVs located.
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'


# Load the standard/smaller files
country_index = pd.read_csv(data_dir + "country Index.csv")
ict_adoption = pd.read_csv(data_dir + "ict adoption by 100 people.csv")
ghs_index = pd.read_csv(data_dir + "2021-GHS-Index-April-2022.csv")
health = pd.read_csv(data_dir + "health.csv")
demographics = pd.read_csv(data_dir + "demographics.csv")
covid_daily = pd.read_csv(data_dir + "WHO-COVID-19-global-daily-data.csv")

print("Standard files loaded successfully!")

# Load the Big files - vaccinations/epidemiology
vaccinations = pd.read_csv(data_dir + "vaccinations.csv")
epidemiology = pd.read_csv(data_dir + "epidemiology.csv")

print("vaccinations/epidemiology BIG files loaded successfully!")

"""### Find which tables has null values and in which fields and how many null value in each field"""

import pandas as pd

# Define the file names for your data science project
datasets = {
    "Country Index": "country Index.csv",
    "Demographics": "demographics.csv",
    "Health Indicators": "health.csv",
    "ICT Adoption": "ict adoption by 100 people.csv",
    "COVID Daily Data": "WHO-COVID-19-global-daily-data.csv",
    "Vaccinations": "vaccinations.csv",
    "Epidemiology": "epidemiology.csv",
    "GHS Index": "2021-GHS-Index-April-2022.csv"
}

# Iterate through each table to evaluate missing values
for name, filepath in datasets.items():
    try:
        # Load dataset using the full path
        df = pd.read_csv(data_dir + filepath)

        print(f"=== Missing Value Analysis: {name} ===")
        print(f"Total Rows: {df.shape[0]} | Total Columns: {df.shape[1]}")

        # Strip potential hidden whitespace in string columns and treat as NaN
        df = df.apply(lambda x: x.str.strip().replace('', pd.NA) if x.dtype == "object" else x)

        # Calculate missing values
        missing_count = df.isna().sum()
        missing_pct = (df.isna().sum() / len(df)) * 100

        # Combine into a summary DataFrame for columns that actually have missing data
        missing_df = pd.DataFrame({
            'Missing Count': missing_count,
            'Percentage (%)': missing_pct
        })

        # Filter to show only columns with at least one missing cell
        missing_summary = missing_df[missing_df['Missing Count'] > 0].round(2)

        if not missing_summary.empty:
            print(missing_summary)
        else:
            print("🎉 Clean table! No empty cells found.")

        print("-" * 50 + "\n")

    except FileNotFoundError:
        print(f"⚠️ File not found: {data_dir + filepath}. Please check your workspace path.\n")

"""## Descriptive Statistic before Merge/Analysis
Here we are running Descriptive statistic - before the merge activity - on each given table of the dataset using describe() pandas function.

**In Pandas, describe()** is a built-in function that automatically computes a comprehensive summary of descriptive statistics for a DataFrame. Instead of writing separate code for the mean, median, min, max, and standard deviation, calling this single function calculates them all at once.

***By default***, it analyzes numerical columns and provides:
*   **count**: Number of non-missing (non-NaN) values.
*   **mean**: The arithmetic average.
*   **std**: Standard deviation (measures how spread out the data is).
*   **min**: The lowest value in the column.
*   **5%, 50%, 75%**: The percentiles (where 50% is the Median).
*   **max**: The highest value in the column.

To capture categorical (text) columns as well, we can use df.describe(include='all'), which adds metrics like unique (count of distinct values) and top (the most frequent value).
"""

# ==================================================
# 1. Descriptive Statistic - country Index.csv
# ==================================================

import pandas as pd

# 1. Load the full source table
df_country_index = pd.read_csv(data_dir + 'country Index.csv')

# 2. Compute full descriptive statistics
stats_country_index = df_country_index.describe(include='all')

# 3. Print the formatted statistical summary table
print("==================================================================")
print("       DESCRIPTIVE STATISTICS SUMMARY: country Index.csv         ")
print("==================================================================")
print(stats_country_index)
print("\n==================================================================")

"""
This table contains static country healthcare metrics and pre-existing medical vulnerabilities (like life expectancy, smoking prevalence, diabetes prevalence, and physician counts).
These features will act as your main baseline risk predictors.
"""

# ==================================================
# 2. Descriptive Statistic - health.csv
# ==================================================

import pandas as pd

# 1. Load the full source table
df_health = pd.read_csv(data_dir + 'health.csv')

# 2. Compute full descriptive statistics
stats_health = df_health.describe(include='all')

# 3. Print the formatted statistical summary table
print("==================================================================")
print("       DESCRIPTIVE STATISTICS SUMMARY: health.csv               ")
print("==================================================================")
print(stats_health)
print("\n==================================================================")

"""
This table contains static structural population distributions across age brackets, density metrics, and development index indicators, which are highly critical for evaluating regional vulnerabilities.
"""

# ==================================================
# 3. Descriptive Statistic - demographics.csv
# ==================================================

import pandas as pd

# 1. Load the full source table
df_demographics = pd.read_csv(data_dir + 'demographics.csv')

# 2. Compute full descriptive statistics
stats_demographics = df_demographics.describe(include='all')

# 3. Print the formatted statistical summary table
print("==================================================================")
print("       DESCRIPTIVE STATISTICS SUMMARY: demographics.csv           ")
print("==================================================================")
print(stats_demographics)
print("\n==================================================================")

"""
This table contains the core global daily tracking indicators for cases and deaths reported directly to the WHO.
"""

# ===============================================================
# 4. Descriptive Statistic - WHO-COVID-19-global-daily-data.csv
# ===============================================================

import pandas as pd

# 1. Load the full source table
df_who_daily = pd.read_csv(data_dir + 'WHO-COVID-19-global-daily-data.csv')

# 2. Compute full descriptive statistics
stats_who_daily = df_who_daily.describe(include='all')

# 3. Print the formatted statistical summary table
print("==================================================================")
print("       DESCRIPTIVE STATISTICS SUMMARY: WHO-COVID-19-global-daily-data.csv")
print("==================================================================")
print(stats_who_daily)
print("\n==================================================================")

"""
This dataset tracks a nation's digital infrastructure capacity over time (mobile subscriptions, internet penetration, etc.), which will allow us to assess how well
technology aided communication and rapid response during the crisis.
"""

# ==================================================
# 5. Descriptive Statistic - ict adoption by 100 people.csv
# ==================================================

import pandas as pd

# 1. Load the full source table
df_ict = pd.read_csv(data_dir + 'ict adoption by 100 people.csv')

# 2. Compute full descriptive statistics
stats_ict = df_ict.describe(include='all')

# 3. Print the formatted statistical summary table
print("==================================================================")
print("       DESCRIPTIVE STATISTICS SUMMARY: ict adoption by 100 people.csv")
print("==================================================================")
print(stats_ict)
print("\n==================================================================")

"""
This table contains the Global Health Security Index dimensions, evaluating countries across critical health security pillars such as early detection, rapid response, compliance
with international norms, and risk environments.
"""

# ==================================================
# 6. Descriptive Statistic - 2021-GHS-Index-April-2022.csv
# ==================================================

import pandas as pd

# 1. Load the full source table
df_ghs = pd.read_csv(data_dir + '2021-GHS-Index-April-2022.csv')

# 2. Compute full descriptive statistics
stats_ghs = df_ghs.describe(include='all')

# 3. Print the formatted statistical summary table
print("==================================================================")
print("       DESCRIPTIVE STATISTICS SUMMARY: 2021-GHS-Index-April-2022.csv")
print("==================================================================")
print(stats_ghs)
print("\n==================================================================")

"""
This is one of the heavy time-series tracking files, containing day-by-day records of confirmed cases, active cases, recoveries, and mortality figures grouped by geographic location identifiers.
"""

# ==================================================
# 7. Descriptive Statistic - epidemiology.csv
# ==================================================

import pandas as pd

# 1. Load the full source table
df_epidemiology = pd.read_csv(data_dir + 'epidemiology.csv')

# 2. Compute full descriptive statistics
stats_epidemiology = df_epidemiology.describe(include='all')

# 3. Print the formatted statistical summary table
print("==================================================================")
print("       DESCRIPTIVE STATISTICS SUMMARY: epidemiology.csv          ")
print("==================================================================")
print(stats_epidemiology)
print("\n==================================================================")

"""
This is the other massive time-series tracking dataset, containing daily metrics on vaccine doses administered, cumulative rollout volumes, and
the count of persons who have completed their vaccination schedule per region.
"""

# ==================================================
# 8. Descriptive Statistic - vaccinations.csv
# ==================================================

import pandas as pd

# 1. Load the full source table
df_vaccinations = pd.read_csv(data_dir + 'vaccinations.csv')

# 2. Compute full descriptive statistics
stats_vaccinations = df_vaccinations.describe(include='all')

# 3. Print the formatted statistical summary table
print("==================================================================")
print("       DESCRIPTIVE STATISTICS SUMMARY: vaccinations.csv          ")
print("==================================================================")
print(stats_vaccinations)
print("\n==================================================================")

"""## Merge common tables and Statistic

### Merge #1: The "Country Profile" merge

This merge combines the primary static reference tables (country Index.csv, health.csv, and demographics.csv) using a standard Inner Join on their shared primary/foreign key field: location_key.

*   **What this brings**: This creates a comprehensive master list of every region’s socio-economic and physical health profile
*   **Exportable Info**: You can export data showing how physicians per 1000 or health expenditure correlates with population density and the Human Development Index
"""

import pandas as pd

# ==========================================
# 1. LOAD THE DATASETS
# ==========================================
df_country_index = pd.read_csv(data_dir + 'country Index.csv')
df_health = pd.read_csv(data_dir + 'health.csv')
df_demographics = pd.read_csv(data_dir + 'demographics.csv')

# ==========================================
# 2. PERFORM THE MERGE IN ONE STEP (CHAINING)
# ==========================================
# We merge df_country_index to df_health, and then immediately merge the result with df_demographics
df_country_profile = pd.merge(df_country_index, df_health, on='location_key', how='inner').merge(df_demographics, on='location_key', how='inner')

print(f"Final Merged Baseline Profile Shape: {df_country_profile.shape}\n")

# ==========================================
# 3. DISPLAY THE TOP 10 ROWS
# ==========================================
print("--- FIRST 10 ROWS OF THE ONE-STEP MERGE COUNTRY BASELINE PROFILE ---")
pd.set_option('display.max_columns', 10)
print(df_country_profile.head(10))

# ==========================================
# 4. DESCRIPTIVE STATISTICS FOR COUNTRY PROFILE
# ==========================================
print("\n" + "=" * 70)
print("     DESCRIPTIVE STATISTICS SUMMARY: df_country_profile")
print("=" * 70)

# 1. Select the core numerical metrics you want to evaluate from this multi-table merge
profile_targets = [
    'population',
    'population_age_80_and_older',
    'hospital_beds',
    'life_expectancy'
]

# Safeguard: filter list to only columns that physically exist in the final dataframe
valid_profile_targets = [col for col in profile_targets if col in df_country_profile.columns]

# 2. EXPLICITLY CALL THE PANDAS DESCRIBE FUNCTION
# We transpose (.T) the result to put the metrics on the rows for easy viewing
summary_stats_profile = df_country_profile[valid_profile_targets].describe().T

# 3. Apply the 3-decimal floating-point configuration requirement
pd.set_option('display.float_format', lambda x: f'{x:.3f}')

# 4. Output the complete statistics table generated by describe()
print(summary_stats_profile)
print("=" * 70)

# 5. Distribution Skewness Check (Example for Life Expectancy)
if 'life_expectancy' in summary_stats_profile.index:
    mean_le = summary_stats_profile.loc['life_expectancy', 'mean']
    median_le = summary_stats_profile.loc['life_expectancy', '50%'] # 50% represents the Median

    print("\n💡 Distribution Insight (life_expectancy):")
    if mean_le > median_le:
        print(f"   Mean ({mean_le:.3f}) > Median ({median_le:.3f}) → Right-skewed distribution!")
    elif mean_le < median_le:
        print(f"   Mean ({mean_le:.3f}) < Median ({median_le:.3f}) → Left-skewed distribution!")
    else:
        print(f"   Mean ({mean_le:.3f}) == Median ({median_le:.3f}) → Perfectly symmetrical distribution!")
print("-" * 70)

"""### **Merge #2: The "COVID-19 Impact & Response" Merge**

This merge combines the reference tables (epidemiology.csv, vaccinations.csv) **using an Outer Join** on their shared primary/foreign key field: location_key/location_key AND date.
**An Outer Join keeps all dates from both files**. If a country has cases in 2020 but no vaccines, it fills the vaccine columns with NaN (Missing values) instead of crashing or deleting the row.

*   **What this brings**: This combines daily viral spread data with daily response (vaccination) metrics.
*   **Exportable Info**: You can analyze the effectiveness of different vaccine brands (Pfizer, Moderna, Sinovac) by exporting a timeline that shows if new_confirmed cases or new_deceased counts dropped following a spike in cumulative_persons_fully_vaccinated.

***Notice***:
Regular inner Join failed because the crash or unexpected result happens due to a specific characteristic of the small sample files you uploaded:
1.   **Zero Date Overlap**: In epidemiology_small_file.csv, the records are all from early 2020 (e.g., 2020-01-01 to 2020-01-10). However, vaccines didn't exist yet, so vaccinations_small_file.csv only contains records starting from 2021 (e.g., 2021-01-25).
2.   **The Result**: When you perform an inner join on both location_key AND date, the resulting DataFrame is completely empty (0 rows). If downstream code tries to perform operations on this empty DataFrame, Python will crash with an error (such as an IndexError or ValueError).

NOT TO USE?
import pandas as pd

# ==========================================
# 1. LOAD THE ENTIRE PRODUCTION DATASETS
# ==========================================
print("Loading datasets into memory...")
df_epi = pd.read_csv(data_dir + 'epidemiology.csv')
df_vac = pd.read_csv(data_dir + 'vaccinations.csv')

print(f"Loaded successfully!")
print(f"-> Full Epidemiology Shape: {df_epi.shape}")
print(f"-> Full Vaccinations Shape: {df_vac.shape}\n")

# ==========================================
# 2. PERFORM TIMELINE MERGE (LOCATION + DATE)
# ==========================================
print("Merging full datasets by Location and Date...")
# We use a 'left' join to keep the entire historical pandemic timeline from epidemiology
# and match vaccine data on the exact dates it became available.
df_pandemic_timeline = pd.merge(
    df_epi,
    df_vac,
    on=['location_key', 'date'],
    how='left'
)

# Chronologically sort the data so time flows correctly for each country
df_pandemic_timeline = df_pandemic_timeline.sort_values(by=['location_key', 'date']).reset_index(drop=True)

# ==========================================
# 3. DATA SCIENCE CLEANUP FOR THE FULL TIMELINE
# ==========================================
# Because vaccines didn't exist in 2020, those days have empty values (NaN).
# We fill those empty tracking metrics with 0.
fill_metrics = [
    'new_persons_vaccinated', 'cumulative_persons_vaccinated',
    'new_vaccine_doses_administered', 'cumulative_vaccine_doses_administered'
]

for col in fill_metrics:
    if col in df_pandemic_timeline.columns:
        df_pandemic_timeline[col] = df_pandemic_timeline[col].fillna(0)

print("Merge complete without errors!")
print(f"Final Combined Timeline Shape: {df_pandemic_timeline.shape}\n")

# ==========================================
# 4. DISPLAY THE TOP 10 ROWS
# ==========================================
print("--- FIRST 10 ROWS OF THE FULL COMBINED TIMELINE ---")
pd.set_option('display.max_columns', 15)
print(df_pandemic_timeline.head(10))
"""

import pandas as pd
import gc

# ==========================================
# 1. OPTIMIZED DATA LOADING
# ==========================================
print("Loading optimized column subsets...")
epi_cols = ['location_key', 'date', 'new_confirmed', 'new_deceased']
vac_cols = ['location_key', 'date', 'new_persons_vaccinated', 'cumulative_persons_vaccinated']

df_epi = pd.read_csv(data_dir + 'epidemiology.csv', usecols=epi_cols)
df_vac = pd.read_csv(data_dir + 'vaccinations.csv', usecols=vac_cols)

df_epi['date'] = pd.to_datetime(df_epi['date'])
df_vac['date'] = pd.to_datetime(df_vac['date'])

print(f"-> Epidemiology baseline rows: {df_epi.shape[0]}")
print(f"-> Vaccinations baseline rows: {df_vac.shape[0]}\n")


# ==========================================
# 2. MERGE A: 'location_key' ONLY (Spatial Alignment - Safe Slice)
# ==========================================
print("Executing Merge A: Spatial-Only (location_key) using a safe RAM footprint...")

# To prevent a many-to-many RAM crash, we take a slice of unique locations
# to cleanly demonstrate the structural join mechanics.
sample_keys = df_epi['location_key'].dropna().unique()[:5]  # Take the first 5 unique location keys
df_epi_slice = df_epi[df_epi['location_key'].isin(sample_keys)]
df_vac_slice = df_vac[df_vac['location_key'].isin(sample_keys)]

df_merge_spatial = pd.merge(
    df_epi_slice,
    df_vac_slice.rename(columns={'date': 'vaccination_date'}),
    on='location_key',
    how='inner'
)

print("-> Merge A Complete (Successfully bypassed RAM crash via geographic slicing)!")
print("--- FIRST 10 ROWS OF MERGE A (GEOGRAPHY ONLY) ---")
print(df_merge_spatial.head(10))
print("-" * 60 + "\n")

# Aggressively clear Merge A elements from memory cache
del df_merge_spatial, df_epi_slice, df_vac_slice
gc.collect()


# ==========================================
# 3. MERGE B: 'location_key' AND 'date' (Full Spatiotemporal)
# ==========================================
print("Executing Merge B: Full Timeline Spatiotemporal (location_key + date)...")

# This join scales linearly because of the compound key matching, so it runs on FULL data safely
df_merge_combined = pd.merge(
    df_epi,
    df_vac,
    on=['location_key', 'date'],
    how='left'
)

# Clean up empty indicators for days prior to vaccine rollouts
fill_cols = ['new_persons_vaccinated', 'cumulative_persons_vaccinated']
df_merge_combined[fill_cols] = df_merge_combined[fill_cols].fillna(0)

df_merge_combined = df_merge_combined.sort_values(by=['location_key', 'date']).reset_index(drop=True)

print("-> Merge B Complete!")
print("--- FIRST 10 ROWS OF MERGE B (GEOGRAPHY + DATE) ---")
print(df_merge_combined.head(10))
print("-" * 60 + "\n")

print("All operations finished cleanly without exceeding environment RAM allocations.")

# ==========================================
# 4. DESCRIPTIVE STATISTICS FOR FULL COMBINED TIMELINE
# ==========================================
print("\n" + "=" * 70)
print("     DESCRIPTIVE STATISTICS SUMMARY: df_merge_combined")
print("=" * 70)

# 1. Select the core numerical metrics from the combined timeline
combined_targets = [
    'new_confirmed',
    'new_deceased',
    'new_persons_vaccinated',
    'cumulative_persons_vaccinated'
]

# Safeguard: filter list to only columns that physically exist in the final dataframe
valid_combined_targets = [col for col in combined_targets if col in df_merge_combined.columns]

# 2. EXPLICITLY CALL THE PANDAS DESCRIBE FUNCTION
# We transpose (.T) the result to put the metrics on the rows for easy auditing
summary_stats_combined = df_merge_combined[valid_combined_targets].describe().T

# 3. Apply the 3-decimal floating-point configuration requirement
pd.set_option('display.float_format', lambda x: f'{x:.3f}')

# 4. Output the complete statistics table generated by describe()
print(summary_stats_combined)
print("=" * 70)

# 5. Distribution Skewness Check (Example for Daily New Confirmed Cases)
if 'new_confirmed' in summary_stats_combined.index:
    mean_nc = summary_stats_combined.loc['new_confirmed', 'mean']
    median_nc = summary_stats_combined.loc['new_confirmed', '50%'] # 50% represents the Median

    print("\n💡 Distribution Insight (new_confirmed):")
    if mean_nc > median_nc:
        print(f"   Mean ({mean_nc:.3f}) > Median ({median_nc:.3f}) → Right-skewed distribution!")
    elif mean_nc < median_nc:
        print(f"   Mean ({mean_nc:.3f}) < Median ({median_nc:.3f}) → Left-skewed distribution!")
    else:
        print(f"   Mean ({mean_nc:.3f}) == Median ({median_nc:.3f}) → Perfectly symmetrical distribution!")
print("-" * 70)

"""### **Merge #3: Technology Adoption**

This merge the full Global Health Security Index (2021-GHS-Index-April-2022.csv) with the full Information and Communications Technology adoption dataset (ict adoption by 100 people.csv) by using **inner join**.

*   **What this brings**: This links a country’s technological infrastructure with its health security preparedness.
*   **Exportable Info**: You can export reports testing the hypothesis that countries with higher Internet users (per 100 people) also have higher scores in the EARLY DETECTION & REPORTING category of the GHS Index
.



"""

import pandas as pd

# ==========================================
# 1. LOAD THE ENTIRE DATASETS
# ==========================================
print("Loading datasets...")
df_ghs = pd.read_csv(data_dir + '2021-GHS-Index-April-2022.csv')
df_ict = pd.read_csv(data_dir + 'ict adoption by 100 people.csv')

print(f"-> GHS Index Shape: {df_ghs.shape}")
print(f"-> ICT Adoption Shape: {df_ict.shape}\n")


# ==========================================
# 2. KEY STANDARDIZATION & PREPARATION
# ==========================================
# To join them cleanly, we align the country columns by renaming 'Entity' in the ICT dataset to 'Country'
df_ict_prepared = df_ict.rename(columns={'Entity': 'Country'})

# Ensure the 'Year' and 'Country' datatypes are matching across both dataframes
df_ghs['Year'] = df_ghs['Year'].astype(int)
df_ict_prepared['Year'] = df_ict_prepared['Year'].astype(int)

df_ghs['Country'] = df_ghs['Country'].astype(str).str.strip()
df_ict_prepared['Country'] = df_ict_prepared['Country'].astype(str).str.strip()


# ==========================================
# 3. PERFORM THE PRODUCTION MERGE
# ==========================================
print("Merging Readiness vs. Technology datasets...")
# We use an inner join to keep rows where we have BOTH technology metrics and preparedness scores for the same country and year.
df_readiness_vs_tech = pd.merge(
    df_ghs,
    df_ict_prepared,
    on=['Country', 'Year'],
    how='inner'
)

# Sort logically for clean viewing and analysis
df_readiness_vs_tech = df_readiness_vs_tech.sort_values(by=['Country', 'Year']).reset_index(drop=True)

print("Merge complete without errors!")
print(f"Final Preparedness vs Tech Shape: {df_readiness_vs_tech.shape}\n")


# ==========================================
# 4. DISPLAY THE TOP 10 ROWS
# ==========================================
print("--- FIRST 10 ROWS OF PREPAREDNESS VS TECHNOLOGY ADOPTION ---")
# Setting options so you can see key target comparison columns in the output printout
columns_to_show = [
    'Country', 'Year', 'OVERALL SCORE',
    '1) PREVENTION OF THE EMERGENCE OR RELEASE OF PATHOGENS',
    'Internet users', 'Mobile phone subscriptions'
]
# Printing only available target columns from the view for a clean layout
available_cols = [col for col in columns_to_show if col in df_readiness_vs_tech.columns]
print(df_readiness_vs_tech[available_cols].head(10))

# ==========================================
# 5. DESCRIPTIVE STATISTICS FOR READINESS VS TECH
# ==========================================
print("\n" + "=" * 70)
print("     DESCRIPTIVE STATISTICS SUMMARY: df_readiness_vs_tech")
print("=" * 70)

# 1. Select the core numerical metrics you want to evaluate from this merge
tech_readiness_targets = [
    'OVERALL SCORE',
    '1) PREVENTION OF THE EMERGENCE OR RELEASE OF PATHOGENS',
    'Internet users',
    'Mobile phone subscriptions'
]

# Safeguard: filter list to only columns that physically exist in the final dataframe
valid_targets = [col for col in tech_readiness_targets if col in df_readiness_vs_tech.columns]

# 2. EXPLICITLY CALL THE PANDAS DESCRIBE FUNCTION
# We transpose (.T) the result to make it an easy-to-read table layout
summary_stats_tech = df_readiness_vs_tech[valid_targets].describe().T

# 3. Apply the 3-decimal floating-point configuration requirement
pd.set_option('display.float_format', lambda x: f'{x:.3f}')

# 4. Output the complete statistics table generated by describe()
print(summary_stats_tech)
print("=" * 70)

# 5. Distribution Skewness Check (Example for OVERALL SCORE)
if 'OVERALL SCORE' in summary_stats_tech.index:
    mean_score = summary_stats_tech.loc['OVERALL SCORE', 'mean']
    median_score = summary_stats_tech.loc['OVERALL SCORE', '50%'] # 50% represents the Median

    print("\n💡 Distribution Insight (OVERALL SCORE):")
    if mean_score > median_score:
        print(f"   Mean ({mean_score:.3f}) > Median ({median_score:.3f}) → Right-skewed distribution!")
    elif mean_score < median_score:
        print(f"   Mean ({mean_score:.3f}) < Median ({median_score:.3f}) → Left-skewed distribution!")
    else:
        print(f"   Mean ({mean_score:.3f}) == Median ({median_score:.3f}) → Perfectly symmetrical distribution!")
print("-" * 70)

"""### **Merge #4: Demographic Vulnerability Analysis**

This merge the full time-series epidemiology tracking data (epidemiology.csv) with the full country/regional demographics baseline data (demographics.csv) using the **primary geographic join key: location_key (Left Join)**.


*   **What this brings**: This applies population characteristics to actual disease outcomes.
*   **Exportable Info**: You can export a list of regions where a high population_age_80_and_older count directly correlates with a higher cumulative_deceased rate per capita.


"""

import pandas as pd

# ==========================================
# 1. LOAD THE ENTIRE PRODUCTION DATASETS
# ==========================================
print("Loading datasets...")
df_epi = pd.read_csv(data_dir + 'epidemiology.csv')
df_demo = pd.read_csv(data_dir + 'demographics.csv')

print(f"-> Full Epidemiology Shape: {df_epi.shape}")
print(f"-> Full Demographics Shape: {df_demo.shape}\n")


# ==========================================
# 2. STEP 1: TIME-SERIES DAILY MERGE
# ==========================================
print("Performing master baseline merge...")
# Standard left join maps static population traits to every matching location row
df_daily_master = pd.merge(
    df_epi,
    df_demo,
    on='location_key',
    how='left'
)

# Feature Engineering: Extract the Year from the string date field
df_daily_master['date'] = pd.to_datetime(df_daily_master['date'])
df_daily_master['Year'] = df_daily_master['date'].dt.year


# ==========================================
# 3. STEP 2: COUNTRY & ANNUAL AGGREGATION
# ==========================================
print("Creating Country-Year aggregate profile...")
# Grouping the full timeline data to get annual sums per country space
df_annual_analysis = df_daily_master.groupby(['location_key', 'Year']).agg({
    'new_confirmed': 'sum',
    'new_deceased': 'sum',
    'population': 'first',                 # Population is static per country
    'population_age_80_and_older': 'first' # Senior metric is static per country
}).reset_index()

# Rename columns to accurately represent annual aggregated data
df_annual_analysis = df_annual_analysis.rename(columns={
    'new_confirmed': 'annual_confirmed',
    'new_deceased': 'annual_deceased'
})


# ==========================================
# 4. STEP 3: VULNERABILITY METRIC CALCULATION
# ==========================================
# Safety check to avoid division-by-zero errors on empty population fields
df_annual_analysis = df_annual_analysis[df_annual_analysis['population'] > 0].copy()

# Compute the normalized 'Deceased Rate Per Capita'
df_annual_analysis['deceased_rate_per_capita'] = (
    df_annual_analysis['annual_deceased'] / df_annual_analysis['population']
)

# Compute normalized senior ratio for better statistical comparison
df_annual_analysis['senior_ratio_per_capita'] = (
    df_annual_analysis['population_age_80_and_older'] / df_annual_analysis['population']
)

print("Processing complete!")
print(f"-> Daily Timeline Rows: {df_daily_master.shape[0]}")
print(f"-> Aggregated Country-Year Rows: {df_annual_analysis.shape[0]}\n")


# ==========================================
# 5. DISPLAY THE TOP 10 ROWS FOR THE COUNTRY-YEAR VIEW
# ==========================================
print("--- FIRST 10 ROWS OF THE COUNTRY-YEAR AGGREGATION ---")
# Adjust formatting options for a clean statistical table output
pd.set_option('display.max_columns', 10)
print(df_annual_analysis.head(10))

# ==========================================
# 6. DESCRIPTIVE STATISTICS FOR MERGED TABLE
# ==========================================
print("\n" + "=" * 60)
print("     DESCRIPTIVE STATISTICS FOR AGGREGATED METRICS")
print("=" * 60)

# Choose the core metrics to analyze from your new table
target_metrics = ['annual_confirmed', 'annual_deceased', 'deceased_rate_per_capita']

# 1. Run the standard describe function for core metrics
# We transpose (.T) the result so metrics are columns and features are rows (cleaner layout)
base_stats = df_annual_analysis[target_metrics].describe().T

# 2. Add the specialized assignment metrics that describe() doesn't include
from scipy import stats
import numpy as np

geom_means = []
trimmed_means = []
modes = []

for col in target_metrics:
    clean_series = df_annual_analysis[col].dropna()

    # Calculate Mode (שכיח)
    modes.append(clean_series.mode()[0] if not clean_series.empty else np.nan)

    # Calculate Geometric Mean (Only for positive non-zero numbers)
    pos_data = clean_series[clean_series > 0]
    geom_means.append(stats.gmean(pos_data) if not pos_data.empty else np.nan)

    # Calculate Trimmed Mean (10% trimmed: 5% off each tail)
    trimmed_means.append(stats.trim_mean(clean_series, 0.05))

# Append the custom series directly into our summary table
base_stats['mode'] = modes
base_stats['geometric_mean'] = geom_means
base_stats['trimmed_mean_10%'] = trimmed_means

# 3. Clean and format the final statistical printout to 2 or 3 decimal places
pd.set_option('display.float_format', lambda x: f'{x:.3f}')
print(base_stats[['count', 'mean', '50%', 'mode', 'geometric_mean', 'trimmed_mean_10%', 'min', 'max']])
print("=" * 60)

# 4. Distribution Analysis Note Example for Deceased Rate Per Capita
mean_dr = base_stats.loc['deceased_rate_per_capita', 'mean']
median_dr = base_stats.loc['deceased_rate_per_capita', '50%']

print("\n💡 Distribution Insights (deceased_rate_per_capita):")
if mean_dr > median_dr:
    print(f"   Mean ({mean_dr:.3f}) > Median ({median_dr:.3f}) → Right-skewed distribution!")
else:
    print(f"   Mean ({mean_dr:.3f}) <= Median ({median_dr:.3f}) → Symmetrical or Left-skewed distribution!")