# -*- coding: utf-8 -*-
"""03_Merge_Static_Base_IsTheWorldReadyForTheNextPandemic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5CPfs0c8D2lBdGeIP3uBySzgNHLMZjY

## IsTheWorldReadyForTheNextPandemic - Mini Project
### Project handled by Liza, Ravit, Hagit and Hodaya

**This notebook includes running of a comprehensive Exploratory Data Analysis (EDA) on base dataSet ready for modeling.**

---
## Part 1 · Setup, data
"""

from google.colab import drive
drive.mount('/content/drive')

# Core imports.
import numpy as np
np.random.seed(42)  # For reproducibility
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set the path where your DataSet CSVs located.
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'

"""## Re-arrainging the data in file "WHO-COVID-19-global-daily-data_md.csv":
1. Turning file "WHO-COVID-19-global-daily-data_md.csv" from date driven to year driven to alighn values
2. Print file EDA
"""

import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם הקובץ (עדכנו את ה-PATH שלכן כאן)
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'  # הכניסו כאן את ה-PATH של הספרייה
FILE_NAME = 'WHO-COVID-19-global-daily-data_md.csv'         # שם הקובץ שלכן

# חיבור אוטומטי של הספרייה והקובץ לנתיב מלא אחד
FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)

print(f"טוען את הקובץ מתוך הנתיב: {FULL_PATH}")

# =====================================================================
# 2. טעינת הקובץ וניקוי ראשוני
# =====================================================================
df = pd.read_csv(FULL_PATH)

# ניקוי רווחים מיותרים משמות העמודות ליתר ביטחון
df.columns = df.columns.str.strip()

# הפיכת עמודת התאריך לפורמט מתאים וחילוץ השנה לקבוצה
df['Date_reported'] = pd.to_datetime(df['Date_reported'], errors='coerce')
df['YEAR'] = df['Date_reported'].dt.year

# =====================================================================
# 3. הגדרת חוקי הקיבוץ (Aggregation Rules)
# =====================================================================
aggregation_rules = {
    'Country_code': 'first',      # שמירת קוד המדינה
    'WHO_region': 'first',        # שמירת האזור הגיאוגרפי
    'New_cases': 'sum',           # סכימת המקרים החדשים לאורך כל השנה
    'New_deaths': 'sum',          # סכימת מקרי המוות החדשים לאורך כל השנה
    'Cumulative_cases': 'max',    # הערך המקסימלי בשנה (סך הכל בסוף השנה)
    'Cumulative_deaths': 'max'    # הערך המקסימלי בשנה (סך הכל בסוף השנה)
}

# =====================================================================
# 4. ביצוע הקיבוץ ושמירת הקובץ השנתי באותה ספרייה
# =====================================================================
df_yearly = df.groupby(['Country', 'YEAR']).agg(aggregation_rules).reset_index()

# שמירת הקובץ החדש באותה הספרייה שהגדרתן למעלה
OUTPUT_NAME = 'yearly_covid_summary.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_yearly.to_csv(OUTPUT_PATH, index=False)

print(f"הטבלה קובצה בהצלחה מרמה יומית לרמה שנתית!")
print(f"הקובץ המעובד נשמר בספרייה שלכן תחת השם: {OUTPUT_NAME}")
print(f"מימדי הטבלה החדשה: {df_yearly.shape}")

# הדפסת 5 השורות הראשונות של הטבלה השנתית המקובצת
print("--- 5 השורות הראשונות בטבלה ---")
display(df_yearly.head(5))

# הדפסת 10 השורות הראשונות של הטבלה השנתית המקובצת
print("\n--- 10 השורות הראשונות בטבלה ---")
display(df_yearly.head(10))

# 1. מדדים סטטיסטיים כלליים (ממוצע, חציון, סטיית תקן, מינימום ומקסימום)
print("--- מדדי מרכז ופיזור עבור העמודות המספריות ---")
# הוספנו .T (טרנספוזיציה) כדי להפוך את הטבלה, מה שיוצר תצוגה הרבה יותר נוחה לקריאה
display(df_yearly.describe().T)

# 2. בדיקת כמות הערכים החסרים (NaN) בכל עמודה
print("\n--- בדיקת ערכים חסרים (Missing Values) בכל עמודה ---")
missing_data = pd.DataFrame({
    'ערכים חסרים (כמות)': df_yearly.isnull().sum(),
    'ערכים חסרים (אחוז)': (df_yearly.isnull().sum() / len(df_yearly)) * 100
})
display(missing_data)

# 3. מדדים ספציפיים נוספים (מדדי גבנוניות וצידוד - Skewness & Kurtosis)
# מדדים אלו חשובים מאוד כדי לדעת אם התפלגות המשתנים שלכן נורמלית או מוטה
print("\n--- מדדי התפלגות מורחבים ---")
extended_stats = pd.DataFrame({
    'Skewness (צידוד)': df_yearly.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_yearly.select_dtypes(include=['number']).kurt()
})
display(extended_stats)

"""## Re-arrainging the data in file "epidemiology_Ind_md.csv":
1. Turning file "epidemiology_Ind_md.csv" from date driven to year driven to alighn values
2. Eliminating "Subregion" fields
3. Assign Null fields = 0
4. Print file EDA
"""

import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם הקובץ האפידמיולוגי
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'  # עדכנו את ה-PATH שלכן כאן
FILE_NAME = 'epidemiology_Ind_md.csv'

FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)
print(f"טוען את הקובץ מתוך: {FULL_PATH}")

# טעינת הקובץ וניקוי רווחים משמות העמודות
df = pd.read_csv(FULL_PATH)
df.columns = df.columns.str.strip()

# =====================================================================
# 2. הסרת עמודות D, E, F, G (לפי אינדקס המיקום שלהן בטבלה)
# =====================================================================
# עמודות D, E, F, G הן עמודות מספר 3, 4, 5, 6 (מתחילים לספור מ-0)
# אלו הן העמודות: subregion1_code, subregion1_name, subregion2_code, subregion2_name
columns_to_drop = [df.columns[3], df.columns[4], df.columns[5], df.columns[6]]
df = df.drop(columns=columns_to_drop)

# =====================================================================
# 3. טיפול בערכים חסרים: החלפת כל ה-NULL / NaN ב-0
# =====================================================================
df = df.fillna(0)

# חילוץ השנה מתוך עמודת התאריך לטובת הקיבוץ
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['YEAR'] = df['date'].dt.year

# =====================================================================
# 4. הגדרת חוקי הקיבוץ השנתי (Aggregation Rules)
# =====================================================================
# אגרגציה לפי לוגיקה של למידת מכונה: נתונים יומיים נסכום, נתונים מצטברים ניקח מקסימום
aggregation_rules = {
    'country_code': 'first',
    'country_name': 'first',
    'aggregation_level': 'first',
    'new_confirmed': 'sum',
    'new_deceased': 'sum',
    'new_recovered': 'sum',
    'new_tested': 'sum',
    'cumulative_confirmed': 'max',
    'cumulative_deceased': 'max',
    'cumulative_recovered': 'max',
    'cumulative_tested': 'max'
}

# =====================================================================
# 5. ביצוע הקיבוץ השנתי ושמירת הקובץ החדש
# =====================================================================
# מקבצים לפי מפתח המדינה (location_key) והשנה (YEAR)
df_yearly = df.groupby(['location_key', 'YEAR']).agg(aggregation_rules).reset_index()

# שמירת הקובץ המעובד באותה ספרייה
OUTPUT_NAME = 'yearly_epidemiology_cleaned.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_yearly.to_csv(OUTPUT_PATH, index=False)

print("\nהפעולות בוצעו בהצלחה!")
print(f"1. עמודות D,E,F,G הוסרו.")
print(f"2. כל ערכי ה-NULL הוחלפו ב-0.")
print(f"3. הנתונים קובצו לרמה שנתית ונשמרו בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה השנתית החדשה: {df_yearly.shape}")

# הדפסת 10 השורות הראשונות של הטבלה המעובדת
print("--- 10 השורות הראשונות בטבלה השנתית הנקייה ---")
display(df_yearly.head(10))

# 1. מדדים סטטיסטיים כלליים (ממוצע, חציון, סטיית תקן, מינימום ומקסימום)
print("--- מדדי מרכז ופיזור עבור העמודות המספריות ---")
# הוספנו .T (טרנספוזיציה) כדי להפוך את הטבלה, מה שיוצר תצוגה הרבה יותר נוחה לקריאה
display(df_yearly.describe().T)

# 2. בדיקת כמות הערכים החסרים (NaN) בכל עמודה
print("\n--- בדיקת ערכים חסרים (Missing Values) בכל עמודה ---")
missing_data = pd.DataFrame({
    'ערכים חסרים (כמות)': df_yearly.isnull().sum(),
    'ערכים חסרים (אחוז)': (df_yearly.isnull().sum() / len(df_yearly)) * 100
})
display(missing_data)

# 3. מדדים ספציפיים נוספים (מדדי גבנוניות וצידוד - Skewness & Kurtosis)
# מדדים אלו חשובים מאוד כדי לדעת אם התפלגות המשתנים שלכן נורמלית או מוטה
print("\n--- מדדי התפלגות מורחבים ---")
extended_stats = pd.DataFrame({
    'Skewness (צידוד)': df_yearly.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_yearly.select_dtypes(include=['number']).kurt()
})
display(extended_stats)

"""## Re-arrainging the data in file "vaccinations_Ind_md.csv":
Re-arrainging the data in file "vaccinations_Ind_md.csv":
1. Turning file "vaccinations_Ind_md.csv" from date driven to year driven to alighn values
2. Eliminating "Subregion" fields
3. Assign Null fields = 0
4. Print file EDA
##
"""

import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם קובץ החיסונים
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'  # עדכנו את ה-PATH שלכן כאן
FILE_NAME = 'vaccinations_Ind_md.csv'

FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)
print(f"טוען את קובץ החיסונים מתוך: {FULL_PATH}")

# טעינת הקובץ וניקוי רווחים משמות העמודות
df_vac = pd.read_csv(FULL_PATH)
df_vac.columns = df_vac.columns.str.strip()

# =====================================================================
# 2. הסרת עמודות D, E, F, G (לפי מיקום העמודה בטבלה)
# =====================================================================
# עמודות 3, 4, 5, 6 הן עמודות ה-subregion הריקות שרואים בתמונה
columns_to_drop = [df_vac.columns[3], df_vac.columns[4], df_vac.columns[5], df_vac.columns[6]]
df_vac = df_vac.drop(columns=columns_to_drop)

# =====================================================================
# 3. מילוי כל השדות הריקים (Null/NaN) ב-0
# =====================================================================
df_vac = df_vac.fillna(0)

# חילוץ השנה מתוך עמודת התאריך לטובת הקיבוץ השנתי
df_vac['date'] = pd.to_datetime(df_vac['date'], errors='coerce')
df_vac['YEAR'] = df_vac['date'].dt.year

# =====================================================================
# 4. בנייה אוטומטית של חוקי הקיבוץ (Aggregation Rules)
# =====================================================================
aggregation_rules = {
    'country_code': 'first',
    'country_name': 'first',
    'aggregation_level': 'first'
}

# סריקה אוטומטית של שאר העמודות בקובץ כדי להתאים sum או max
for col in df_vac.columns:
    if col in ['location_key', 'date', 'YEAR', 'country_code', 'country_name', 'aggregation_level']:
        continue

    # אם העמודה מייצגת נתון מצטבר, ניקח את הערך המקסימלי השנתי
    if 'cumulative' in col.lower() or 'total' in col.lower():
        aggregation_rules[col] = 'max'
    # אם העמודה מייצגת נתון יומי חדש, נסכום את כל השנה
    else:
        aggregation_rules[col] = 'sum'

# =====================================================================
# 5. ביצוע הקיבוץ (Groupby) ושמירת הקובץ השנתי המעובד
# =====================================================================
df_vac_yearly = df_vac.groupby(['location_key', 'YEAR']).agg(aggregation_rules).reset_index()

# שמירת הקובץ המעובד באותה ספרייה
OUTPUT_NAME = 'yearly_vaccinations_final_summary.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_vac_yearly.to_csv(OUTPUT_PATH, index=False)

print("\n--- קובץ החיסונים עובד בהצלחה בהתאם לכל הדרישות! ---")
print(f"1. עמודות ה-subregion (D,E,F,G) הוסרו בהצלחה.")
print(f"2. כל השדות הריקים מולאו ב-0.")
print(f"3. עמודות מסוג Cumulative/Total קיבלו ערך מקסימלי, ועמודות מסוג New נסכמו שנתית.")
print(f"4. הקובץ השנתי נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה החדשה: {df_vac_yearly.shape}")

# הדפסת 10 השורות הראשונות של טבלת החיסונים המעובדת
print("--- 10 השורות הראשונות בטבלת החיסונים השנתית ---")
display(df_vac_yearly.head(10))

# 1. מדדי מרכז ופיזור (ממוצע, חציון, סטיית תקן, מינימום, מקסימום ואחוזונים)
print("--- מדדי מרכז ופיזור עבור עמודות החיסונים והתגובה ---")
# שימוש ב-.T הופך את הטבלה כדי שיהיה קל לקרוא את המדדים עבור עמודות החיסונים הארוכות
display(df_vac_yearly.describe().T)

# 2. וידאו סופי שאין יותר ערכים חסרים (התוצאה בכל העמודות צריכה להיות 0)
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ החיסונים המעובד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_vac_yearly.isnull().sum(),
    'אחוז ערכי NULL': (df_vac_yearly.isnull().sum() / len(df_vac_yearly)) * 100
})
display(missing_summary)

# 3. מדדי התפלגות (צידוד וגבנוניות - Skewness & Kurtosis)
print("\n--- מדדי התפלגות מורחבים של עמודות החיסונים ---")
distribution_stats = pd.DataFrame({
    'Skewness (צידוד)': df_vac_yearly.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_vac_yearly.select_dtypes(include=['number']).kurt()
})
display(distribution_stats)

"""## Re-arrainging the data in file "demographic_Ind_md.csv":
Re-arrainging the data in file "demographic_Ind_md.csv":
1. Eliminating "Subregion" fields
2. Assign Null fields = median
3. Print file EDA
##
"""

import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם קובץ הדמוגרפיה (עם תיקון הסיומת)
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
FILE_NAME = 'demographics_Ind_md.csv'

FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)
print(f"טוען את קובץ הדמוגרפיה מתוך: {FULL_PATH}")

# טעינת הקובץ וניקוי רווחים משמות העמודות
df_new = pd.read_csv(FULL_PATH)
df_new.columns = df_new.columns.str.strip()

# =====================================================================
# 2. הסרת עמודות D, E, F, G (עמודות באינדקסים 3, 4, 5, 6)
# =====================================================================
# משיכת שמות העמודות המדויקים לפי המיקום שלהן בטבלה
columns_to_drop = [df_new.columns[3], df_new.columns[4], df_new.columns[5], df_new.columns[6]]
df_demo_cleaned = df_new.drop(columns=columns_to_drop)

# =====================================================================
# 3. מילוי כל השדות הריקים (Null / NaN) בחציון של כל עמודה
# =====================================================================
# המשתנה numeric_only=True מבטיח חישוב חציון רק לעמודות עם מספרים ומניעת שגיאות
column_medians = df_demo_cleaned.median(numeric_only=True)
df_demo_cleaned = df_demo_cleaned.fillna(column_medians)

# =====================================================================
# 4. שמירת קובץ הדמוגרפיה הנקי באותה ספרייה
# =====================================================================
OUTPUT_NAME = 'cleaned_demographics_final.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_demo_cleaned.to_csv(OUTPUT_PATH, index=False)

print("\n--- הריצה הסתיימה בהצלחה! הקובץ נוקה ונשמר ---")
print(f"הקובץ הנקי נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה (שורות, עמודות): {df_demo_cleaned.shape}")

# =====================================================================
# 5. הדפסת 10 השורות הראשונות לבדיקה ויזואלית סופית
# =====================================================================
print("\n--- 10 השורות הראשונות בטבלת הדמוגרפיה הנקייה ---")
display(df_demo_cleaned.head(10))

# 1. מדדי מרכז ופיזור (ממוצע, חציון, סטיית תקן, מינימום, מקסימום ואחוזונים)
print("--- מדדי מרכז ופיזור עבור נתוני האוכלוסייה והדמוגרפיה ---")
# שימוש ב-.T הופך את הטבלה כדי שיהיה קל לקרוא את המדדים עבור פלחי הגיל הרבים
display(df_demo_cleaned.describe().T)

# 2. וידאו סופי שאין יותר ערכים חסרים (התוצאה בכל העמודות צריכה להיות 0)
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ הדמוגרפיה המעובד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_demo_cleaned.isnull().sum(),
    'אחוז ערכי NULL': (df_demo_cleaned.isnull().sum() / len(df_demo_cleaned)) * 100
})
display(missing_summary)

# 3. מדדי התפלגות (צידוד וגבנוניות - Skewness & Kurtosis)
print("\n--- מדדי התפלגות מורחבים של עמודות הדמוגרפיה ---")
distribution_stats = pd.DataFrame({
    'Skewness (צידוד)': df_demo_cleaned.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_demo_cleaned.select_dtypes(include=['number']).kurt()
})
display(distribution_stats)

"""## Re-arrainging the data in file "health_Demog_Ind_md.csv":
Re-arrainging the data in file "health_Demog_Ind_md.csv":
1. Eliminating "Subregion" fields
2. Assign Null fields = median
3. Print file EDA
##
"""

import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם קובץ הבריאות והדמוגרפיה
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
FILE_NAME = 'health_Demog_Ind_md.csv'  # שם הקובץ שביקשתן לנקות

FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)
print(f"טוען את קובץ הבריאות והדמוגרפיה מתוך: {FULL_PATH}")

# טעינת הקובץ וניקוי רווחים מיותרים משמות העמודות
df_health_demo = pd.read_csv(FULL_PATH)
df_health_demo.columns = df_health_demo.columns.str.strip()

# =====================================================================
# 2. הסרת עמודות D, E, F, G (עמודות באינדקסים 3, 4, 5, 6)
# =====================================================================
# שמות העמודות subregion1_code, subregion1_name, subregion2_code, subregion2_name
columns_to_drop = [
    df_health_demo.columns[3],
    df_health_demo.columns[4],
    df_health_demo.columns[5],
    df_health_demo.columns[6]
]
df_health_demo_cleaned = df_health_demo.drop(columns=columns_to_drop)

# =====================================================================
# 3. מילוי כל השדות הריקים (Null / NaN) בחציון של כל עמודה
# =====================================================================
# numeric_only=True מבטיח חישוב חציון רק לעמודות מספריות ומונע שגיאות בעמודות טקסט
column_medians = df_health_demo_cleaned.median(numeric_only=True)
df_health_demo_cleaned = df_health_demo_cleaned.fillna(column_medians)

# =====================================================================
# 4. שמירת הקובץ הנקי החדש באותה ספרייה
# =====================================================================
OUTPUT_NAME = 'cleaned_health_demographics_final.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_health_demo_cleaned.to_csv(OUTPUT_PATH, index=False)

print("\n--- הקובץ עובד ונוקה בהצלחה! ---")
print(f"1. עמודות D, E, F, G הוסרו מהטבלה.")
print(f"2. כל השדות הריקים מולאו בחציון של כל עמודה.")
print(f"3. הקובץ הנקי נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה החדשה (שורות, עמודות): {df_health_demo_cleaned.shape}")

# =====================================================================
# 5. הדפסת 10 השורות הראשונות לבדיקה ויזואלית סופית
# =====================================================================
print("\n--- 10 השורות הראשונות בטבלה הנקייה ---")
display(df_health_demo_cleaned.head(10))

# 1. מדדי מרכז ופיזור (ממוצע, חציון, סטיית תקן, מינימום, מקסימום ואחוזונים)
print("--- מדדי מרכז ופיזור עבור נתוני הבריאות והחוסן הרפואי ---")
# שימוש ב-.T הופך את הטבלה כדי שתוכלו לקרוא בנוחות את המדדים עבור המשתנים הרבים (רופאים, מיטות וכו')
display(df_health_demo_cleaned.describe().T)

# 2. וידאו סופי שאין יותר ערכים חסרים (התוצאה בכל העמודות צריכה להיות 0)
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ הבריאות המעובד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_health_demo_cleaned.isnull().sum(),
    'אחוז ערכי NULL': (df_health_demo_cleaned.isnull().sum() / len(df_health_demo_cleaned)) * 100
})
display(missing_summary)

# 3. מדדי התפלגות (צידוד וגבנוניות - Skewness & Kurtosis)
print("\n--- מדדי התפלגות מורחבים של עמודות הבריאות ---")
distribution_stats = pd.DataFrame({
    'Skewness (צידוד)': df_health_demo_cleaned.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_health_demo_cleaned.select_dtypes(include=['number']).kurt()
})
display(distribution_stats)



"""## Re-arrainging the data in file "ICT_GHS_Ind_md.csv":
Re-arrainging the data in file "ICT_GHS_Ind_md":
1. Eliminating "Subregion" fields
2. Print file EDA
##
"""

import os
import pandas as pd

# =====================================================================
# 1. הגדרת נתיב הספרייה ושם הקובץ הטכנולוגי (ICT ו-GHS)
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
FILE_NAME = 'ICT_GHS_Ind_md.csv'  # שם הקובץ המדויק שציינתן

FULL_PATH = os.path.join(FOLDER_PATH, FILE_NAME)
print(f"טוען את הקובץ מתוך: {FULL_PATH}")

# טעינת הקובץ וניקוי רווחים מיותרים משמות העמודות ליתר ביטחון
df_ict_ghs = pd.read_csv(FULL_PATH)
df_ict_ghs.columns = df_ict_ghs.columns.str.strip()

# =====================================================================
# 2. הסרת עמודות K, L, M, N (עמודות באינדקסים 10, 11, 12, 13)
# =====================================================================
# משיכת שמות עמודות ה-subregion לפי מיקומן המדויק (K=10, L=11, M=12, N=13)
columns_to_drop = [
    df_ict_ghs.columns[10],
    df_ict_ghs.columns[11],
    df_ict_ghs.columns[12],
    df_ict_ghs.columns[13]
]
df_ict_ghs_cleaned = df_ict_ghs.drop(columns=columns_to_drop)

# =====================================================================
# 3. מילוי כל השדות הריקים (Null / NaN) במספר 0
# =====================================================================
df_ict_ghs_cleaned = df_ict_ghs_cleaned.fillna(0)

# =====================================================================
# 4. שמירת הקובץ הנקי החדש באותה ספרייה
# =====================================================================
OUTPUT_NAME = 'cleaned_ICT_GHS_final.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)
df_ict_ghs_cleaned.to_csv(OUTPUT_PATH, index=False)

print("\n--- הקובץ עובד ונוקה בהצלחה! ---")
print(f"1. עמודות K, L, M, N (עמודות המחוזות) הוסרו מהטבלה.")
print(f"2. כל השדות הריקים מולאו ב-0.")
print(f"3. הקובץ הנקי נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה החדשה (שורות, עמודות): {df_ict_ghs_cleaned.shape}")

# =====================================================================
# 5. הדפסת 10 השורות הראשונות לבדיקה ויזואלית סופית
# =====================================================================
print("\n--- 10 השורות הראשונות בטבלת הטכנולוגיה והמדדים הנקייה ---")
display(df_ict_ghs_cleaned.head(10))

# 1. מדדי מרכז ופיזור (ממוצע, חציון, סטיית תקן, מינימום, מקסימום ואחוזונים)
print("--- מדדי מרכז ופיזור עבור מדדי הטכנולוגיה וביטחון הבריאות (GHSI) ---")
# שימוש ב-.T הופך את הטבלה ומקל מאוד על קריאת המדדים של תתי-הקטגוריות הרבות במדד ה-GHS
display(df_ict_ghs_cleaned.describe().T)

# 2. וידאו סופי שאין ערכים חסרים (התוצאה בכל העמודות צריכה להיות 0)
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ ה-ICT וה-GHS המעובד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_ict_ghs_cleaned.isnull().sum(),
    'אחוז ערכי NULL': (df_ict_ghs_cleaned.isnull().sum() / len(df_ict_ghs_cleaned)) * 100
})
display(missing_summary)

# 3. מדדי התפלגות (צידוד וגבנוניות - Skewness & Kurtosis)
print("\n--- מדדי התפלגות מורחבים של עמודות הטכנולוגיה והמדדים ---")
distribution_stats = pd.DataFrame({
    'Skewness (צידוד)': df_ict_ghs_cleaned.select_dtypes(include=['number']).skew(),
    'Kurtosis (גבנוניות)': df_ict_ghs_cleaned.select_dtypes(include=['number']).kurt()
})
display(distribution_stats)

"""## Merging File "vaccinations_Ind_md.csv" with file "epidemiology_Ind_md.csv":
1. Merging the two files into one file with fully outer join:
2. Print first 10 lines and statistices
##
"""

import os
import pandas as pd

# יצירת כינוי תואם לקובץ האפידמיולוגיה השנתי בזיכרון
df_epi_yearly = df_yearly.copy()

# (בהנחה ששני המשתנים df_epi_yearly ו-df_vac_yearly קיימים כרגע בזיכרון שלכן)

# =====================================================================
# 1. הגדרת העמודות המשותפות שאין צורך לשכפל (עמודות מזהות)
# =====================================================================
# לפני המיזוג, נוריד את country_code ו-country_name מטבלת החיסונים
# כדי שלא נקבל עמודות כפולות כמו country_name_x ו-country_name_y
cols_to_drop_from_vac = ['country_code', 'country_name', 'aggregation_level']
df_vac_filtered = df_vac_yearly.drop(columns=[col for col in cols_to_drop_from_vac if col in df_vac_yearly.columns])

# =====================================================================
# 2. ביצוע ה-Full Outer Join לפי מדינה (location_key) ושנה (YEAR)
# =====================================================================
print("מבצע מיזוג חיצוני מלא (Full Outer Join)...")
df_merged_2 = pd.merge(
    df_epi_yearly,
    df_vac_filtered,
    on=['location_key', 'YEAR'],
    how='outer'
)

# =====================================================================
# 3. ניקוי שלאחר המיזוג: מילוי ערכי NaN שנוצרו מה-Outer Join
# =====================================================================
# בעקבות החיבור החיצוני, שורות שלא התאימו בשתי הטבלאות יקבלו NaN. נשלים אותן ל-0.
df_merged_2 = df_merged_2.fillna(0)

# =====================================================================
# 4. שמירת הקובץ המאוחד החדש
# =====================================================================
# הגדירו את ה-PATH שלכן לשמירה
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
OUTPUT_NAME = 'merged_epidemiology_vaccinations_yearly_md.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)

df_merged_2.to_csv(OUTPUT_PATH, index=False)

print(f"\n--- המיזוג (מיזוג 2) הסתיים בהצלחה! ---")
print(f"הקובץ המאוחד נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה המאוחדת (שורות, עמודות): {df_merged_2.shape}")

# =====================================================================
# 1. הדפסת 10 השורות הראשונות של הטבלה המאוחדת החדשה
# =====================================================================
print("--- 10 השורות הראשונות בטבלה המאוחדת (אפידמיולוגיה + חיסונים) ---")
display(df_merged_2.head(10))

# =====================================================================
# 2. הפקת מדדים סטטיסטיים מקיפים (מרכז ופיזור)
# =====================================================================
print("\n--- מדדי מרכז ופיזור עבור כל העמודות המספריות בטבלה המאוחדת ---")
# שימוש ב-.T (טרנספוזיציה) הופך את הטבלה ומקל על קריאת עמודות התחלואה והחיסונים יחד
display(df_merged_2.describe().T)

# =====================================================================
# 3. וידאו סופי שאין ערכים חסרים (NaN) לאחר פעולת ה-fillna
# =====================================================================
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ המאוחד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_merged_2.isnull().sum(),
    'אחוז ערכי NULL': (df_merged_2.isnull().sum() / len(df_merged_2)) * 100
})
display(missing_summary)

"""## Merging File "epidemiology_Ind_md.csv" with file "demographic_Ind_md.csv" with file:
1. Merging the two files into one file with Left join in order to maintain all
data.
2. Print first 10 lines and statistices
3. Calculating X4 = New Tested / Population * 1000 (Normalized)
##
"""

import os
import pandas as pd

# (בהנחה ששני המשתנים df_yearly ו-df_demo_cleaned קיימים כרגע בזיכרון שלכן)

# =====================================================================
# 1. ניקוי עמודות כפולות מטבלת הדמוגרפיה לפני החיבור
# =====================================================================
cols_to_drop_from_demo = ['country_code', 'country_name', 'aggregation_level']
df_demo_filtered = df_demo_cleaned.drop(columns=[col for col in cols_to_drop_from_demo if col in df_demo_cleaned.columns])

# =====================================================================
# 2. ביצוע ה-Left Join לפי מפתח המדינה (location_key)
# =====================================================================
print("מבצע מיזוג שמאלי (Left Join) של נתוני אפידמיולוגיה ודמוגרפיה...")
df_epidemiology_demographics = pd.merge(
    df_yearly,          # טבלת הבסיס השנתית (האפידמיולוגית)
    df_demo_filtered,   # טבלת הדמוגרפיה המסוננת
    on='location_key',  # החיבור מתבצע לפי מפתח המדינה
    how='left'          # שמירה על כל שורות התחלואה והתאמת הדמוגרפיה אליהן
)

# =====================================================================
# 3. ניקוי שלאחר המיזוג: מילוי ערכים חסרים (NaN) מבוקר ולא גורף
# =====================================================================
# נמלא ב-0 רק עמודות של מונים אפידמיולוגיים יומיים/שנתיים שבהם NaN מייצג אפס מקרים
cols_to_fill_zero = ['new_confirmed', 'new_deceased', 'total_confirmed', 'total_deceased']
for col in cols_to_fill_zero:
    if col in df_epidemiology_demographics.columns:
        df_epidemiology_demographics[col] = df_epidemiology_demographics[col].fillna(0)

# שאר עמודות השיעורים, המדדים והתמותה העודפת נשארות כ-NaN כדי לא לעוות את הנתונים

# =====================================================================
# 4. שמירת הקובץ המאוחד החדש
# =====================================================================
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
OUTPUT_NAME = 'merged_epidemiology_demographics_yearly.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)

df_epidemiology_demographics.to_csv(OUTPUT_PATH, index=False)

print(f"\n--- המיזוג (מיזוג 4 בתוכנית) הסתיים בהצלחה! ---")
print(f"הקובץ המאוחד נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה המאוחדת החדשה (שורות, עמודות): {df_epidemiology_demographics.shape}")

# =====================================================================
# 1. הדפסת 10 השורות הראשונות של הטבלה המאוחדת החדשה
# =====================================================================
print("--- 10 השורות הראשונות בטבלה המאוחדת (אפידמיולוגיה + דמוגרפיה) ---")
display(df_epidemiology_demographics.head(10))

# =====================================================================
# 2. הפקת מדדים סטטיסטיים מקיפים (מרכז ופיזור)
# =====================================================================
print("\n--- מדדי מרכז ופיזור עבור כל העמודות המספריות בטבלה המאוחדת ---")
# שימוש ב-.T (טרנספוזיציה) הופך את הטבלה ומקל על קריאת עמודות התחלואה והדמוגרפיה יחד
display(df_epidemiology_demographics.describe().T)

# =====================================================================
# 3. וידאו סופי שאין ערכים חסרים (NaN) לאחר פעולת ה-Left Join
# =====================================================================
print("\n--- בדיקת ערכים חסרים (Missing Values) בקובץ המאוחד ---")
missing_summary = pd.DataFrame({
    'כמות ערכי NULL': df_epidemiology_demographics.isnull().sum(),
    'אחוז ערכי NULL': (df_epidemiology_demographics.isnull().sum() / len(df_epidemiology_demographics)) * 100
})
display(missing_summary)

import os
import pandas as pd

# הגדרת ה-PATH שלכן לשמירה ב-Google Drive
FOLDER_PATH = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
OUTPUT_NAME = 'merged_epidemiology_demographics_yearly.csv'
OUTPUT_PATH = os.path.join(FOLDER_PATH, OUTPUT_NAME)

print("1. מכין את משתני הזיכרון המקוריים...")
# יצירת עותקים נקיים וניקוי רווחים נסתרים משמות העמודות
df_epi_base = df_yearly.copy()
df_epi_base.columns = df_epi_base.columns.str.strip()

df_demo_base = df_demo_cleaned.copy()
df_demo_base.columns = df_demo_base.columns.str.strip()

# =====================================================================
# 2. ניקוי עמודות כפולות מטבלת הדמוגרפיה לפני החיבור
# =====================================================================
cols_to_drop_from_demo = ['country_code', 'country_name', 'aggregation_level']
df_demo_filtered = df_demo_base.drop(columns=[col for col in cols_to_drop_from_demo if col in df_demo_base.columns])

# =====================================================================
# 3. ביצוע ה-Left Join לפי מפתח המדינה (location_key) - שמירה על כל העמודות
# =====================================================================
print("2. מבצע מיזוג שמאלי (Left Join) ושומר על כל העמודות המקוריות...")
df_epidemiology_demographics = pd.merge(
    df_epi_base,        # טבלת הבסיס השנתית האפידמיולוגית
    df_demo_filtered,   # טבלת הדמוגרפיה המסוננת
    on='location_key',  # החיבור מתבצע לפי מפתח המדינה
    how='left'          # שמירה על כל שורות התחלואה והתאמת הדמוגרפיה אליהן
)

# =====================================================================
# 4. חישוב משתנה X4 המדויק על בסיס העמודה new_tested
# =====================================================================
print("3. מחשב את משתנה X4 (סך בדיקות ל-1,000 איש) מתוך עמודת new_tested...")

# וידוא ששני השדות קיימים בטבלה המשולבת
if 'new_tested' in df_epidemiology_demographics.columns and 'population' in df_epidemiology_demographics.columns:
    # חישוב הנוסחה: (בדיקות חלקי אוכלוסייה) כפול 1,000
    df_epidemiology_demographics['X4'] = (df_epidemiology_demographics['new_tested'] / df_epidemiology_demographics['population']) * 1000

    # טיפול במצבים של חלוקה באפס (אם יש מדינה עם אוכלוסייה 0) או ערכים חסרים
    df_epidemiology_demographics['X4'] = df_epidemiology_demographics['X4'].fillna(0)
else:
    print("שגיאה: העמודות new_tested או population לא נמצאו בטבלה!")

# =====================================================================
# 5. ניקוי שלאחר המיזוג: מילוי ערכים חסרים (NaN) מבוקר (לא גורף)
# =====================================================================
# נמלא ב-0 רק עמודות של מונים אפידמיולוגיים יומיים/שנתיים
cols_to_fill_zero = ['new_confirmed', 'new_deceased', 'new_recovered', 'new_tested',
                     'cumulative_confirmed', 'cumulative_deceased', 'cumulative_recovered', 'cumulative_tested']

for col in cols_to_fill_zero:
    if col in df_epidemiology_demographics.columns:
        df_epidemiology_demographics[col] = df_epidemiology_demographics[col].fillna(0)

# עמודות המדדים, האחוזים והתמותה העודפת נשארות כפי שהן לטיפול בחציון בשלבים הבאים

# =====================================================================
# 6. שמירת הקובץ המתוקן והמלא ל-Google Drive
# =====================================================================
df_epidemiology_demographics.to_csv(OUTPUT_PATH, index=False)

print(f"\n--- הקובץ שוחזר, חושב ותוקן בהצלחה! ---")
print(f"הקובץ המלא נשמר בשם: {OUTPUT_NAME}")
print(f"מימדי הטבלה המשוחזרת (שורות, עמודות כולל X4): {df_epidemiology_demographics.shape}")

print(df_merged_4.columns.tolist())